### ISSUE TITLE
Installing PluXml on root

### ISSUE THREAD

**Issue by scith** [matlink/pluxml_ynh#12]
Hello,
I have a bug when trying to install PluXml on the path "/" (root of a domain).
I think it breaks the install script and the nginx file. In the Nginx file I have things like "//data" (one extra trailing slash.

I look at the install script and I think the same problem occurs: 
curl -kL -o install_page.html https://DOMAIN//install.php

I think at some point you need to add: "path=${path%/}" to remove the trailing slash.

Thanks

**Comment by scith** [comment]
Even without the trailing slash it seems that the install script cannot be ran. I don't know why, if I put the install.php file back in the folder after the app was installed, I can run the functions in the script and it works.

In the app install log, the "token" is empty however.

**Comment by matlink** [comment]
Let me take a look at it, I'll come back to you if I find something 
concrete.

**Comment by matlink** [comment]
Check the last commit, it should do the trick.

**Comment by scith** [comment]
It works great thanks :)
Now I can install several PluXml on various subdomains!

**Comment by matlink** [comment]
.htaccess is obsolete with nginx, since it does not use this kind of file to manage writes. Finally I'm removing it since this is sensless.
