### ISSUE TITLE
Block logs,version,configuration

### ISSUE THREAD

**Issue by src386** [matlink/pluxml_ynh#14]
I suggest add this : 

    location ~ /(version|configuration|logs)$ {
                return 403;
        }

Didnt tried the packaged, just had a look at the nginx.conf :)

Note : this is for standard vhost, not for Yunohost splited apps nginx conf.

**Comment by matlink** [comment]
`configuration` and `logs` do not exist aren't they?

**Comment by src386** [comment]
It has been a long time, honestly I don't remember what was in my mind.
Yeah nginx.conf is okay, never mind.
