### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by anmol26s** [matlink/pluxml_ynh#9]
Hi Matlink

Its been long time, since this application has been updated. Will you update it?
The comment have a bug and people spam in the comments.

Moreover in /etc/nginx/conf.d/domain.tld.d/pluxml.conf  needs to added with the line "fastcgi_param SCRIPT_FILENAME $request_filename;" , so to work with updated yunohost.

**Comment by matlink** [comment]
Thanks for report. I'm gonna have a look on it right now.

**Comment by anmol26s** [comment]
Hi
There is an updatefor pluXml. http://telechargements.pluxml.org/changelog
Can you please update.
Thanks

**Comment by matlink** [comment]
Should be ok. Make sure to build a backup before upgrading please. And report any issue thank you :)
